export const defaultRSX = {
	appName: '---',
	appVersion: '---',
	jreAvailableProcessors: 0,
	jreFreeMemory: 0,
	jreVersion: '---',
	jreMaxMemory: 0,
	jreTotalMemory: 0,
	latestMilestone: '---',
	latestMilestoneIndex: 0,
	latestSolidSubtangleMilestone: '---',
	latestSolidSubtangleMilestoneIndex: 0,
	milestoneStartIndex: 0,
	lastSnapshottedMilestoneIndex: 0,
	neighbors: 0,
	packetsQueueSize: 0,
	time: 0,
	tips: 0,
	transactionsToRequest: 0,
	features: ['---'],
	coordinatorAddress: '---',
	duration: 0,
	state: false
}
